#!/usr/bin/env bash
# detections/siem/gen-siem.sh — generate the deployable Splunk savedsearches form
# from the Sigma source of truth, so the compiled deploy artifact stops drifting.
# ──────────────────────────────────────────────────────────────────────────────
# Sigma is the source of truth (detections/sigma/). This script is the reproducible
# "compile Sigma → backend, in its DEPLOY shape" step: it runs the pySigma splunk
# backend's `savedsearches` output format over the whole rule tree and writes one
# savedsearches.conf a Splunk app can drop into etc/apps/<app>/local/. It is the
# generated twin of the hand-authored deploy forms alongside it:
#
#   splunk/savedsearches.generated.conf   ← THIS SCRIPT (every single-event +
#                                            correlation rule, drift-gated in CI)
#   splunk/savedsearches.conf             ← hand, 5 enriched worked examples
#   splunk/correlation_searches.conf      ← hand, absence/join detections Sigma
#                                            can't express (Golden/Silver/NTLM-relay)
#   sentinel/*.yaml                        ← hand, Microsoft Sentinel deploy forms
#
# Windows tactic dirs compile through the `splunk_windows` pipeline (EventID→EventCode
# and the Splunk Windows TA field names); the non-Windows platform dirs compile raw
# (--without-pipeline), matching detections/sigma/convert.sh.
#
#   gen-siem.sh            # (re)write splunk/savedsearches.generated.conf from sigma/
#   gen-siem.sh --check    # exit 1 (with a diff) if the committed file is out of date
#
# --check is the drift gate (CI runs it in .github/workflows/sigma.yml); the bare form
# is what you run after adding/editing a rule. Deps: sigma-cli + pysigma-backend-splunk
# (same pins as convert.sh / the CI job).
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)"
SIGMA="$HERE/../sigma"
OUT="$HERE/splunk/savedsearches.generated.conf"

CHECK=0
if [[ $# -gt 1 ]]; then
  echo "gen-siem: too many arguments" >&2
  echo "usage: gen-siem.sh [--check]" >&2
  exit 2
fi
case "${1:-}" in
"") CHECK=0 ;;
--check) CHECK=1 ;;
*)
  echo "gen-siem: unknown argument '$1'" >&2
  echo "usage: gen-siem.sh [--check]" >&2
  exit 2
  ;;
esac

if ! command -v sigma >/dev/null 2>&1; then
  echo "sigma not found — pip install sigma-cli pysigma-backend-splunk" >&2
  exit 1
fi

# Windows tactic dirs → splunk_windows TA pipeline; non-Windows platform dirs → raw.
# (Same split convert.sh documents; kept explicit so a new dir is a conscious choice.)
WIN_DIRS=(credential_access privilege_escalation lateral_movement persistence defense_evasion)
NONWIN_DIRS=(cloud kubernetes okta github gitlab registry vault terraform jenkins snowflake)

# Each `sigma convert -f savedsearches` invocation prepends its own [default] stanza
# (global dispatch window). Strip every per-invocation [default] block and emit one
# canonical [default] at the top instead, so the concatenated file has exactly one.
# Drop the per-invocation [default] stanza (a global dispatch window sigma emits once
# per convert call); one canonical [default] is written in the header instead. Skip
# from the [default] header until the NEXT stanza header (^[) — not the next blank line,
# which would be brittle if the upstream format ever reflowed blank lines.
strip_default() {
  awk '
    /^\[default\]$/ { skip=1; next }
    skip && /^\[/   { skip=0 }
    skip            { next }
    { print }
  '
}

# Compile one rule dir to savedsearches stanzas. Rules are passed as an explicit,
# byte-sorted file list (NOT the bare directory): `sigma convert <dir>` enumerates in
# filesystem order, which differs between machines and would make the generated file —
# and therefore the --check drift gate — non-reproducible across environments.
#   $1 = dir under sigma/   $2… = extra `sigma convert` args (pipeline selection)
gen_dir() {
  local dir="$1"
  shift
  [[ -d "$SIGMA/$dir" ]] || return 0
  local files=()
  mapfile -t files < <(find "$SIGMA/$dir" -maxdepth 1 -name '*.yml' | LC_ALL=C sort)
  [[ ${#files[@]} -gt 0 ]] || return 0
  # No stderr suppression: sigma's "Parsing Sigma rules" notice goes to stderr (it does
  # not pollute the generated stdout), and a real conversion error must stay visible —
  # with pipefail it also fails the pipeline so the drift gate reports the root cause.
  sigma convert -t splunk -f savedsearches "$@" "${files[@]}" | strip_default
}

generate() {
  cat <<'HEADER'
# savedsearches.generated.conf — GENERATED by detections/siem/gen-siem.sh. DO NOT EDIT.
#
# Reproducible compile of every Sigma rule in detections/sigma/ to its Splunk
# savedsearches deploy form. Regenerate with detections/siem/gen-siem.sh; CI drift-gates
# it with `gen-siem.sh --check`. Windows dirs use the splunk_windows TA pipeline; the
# non-Windows platform dirs compile with raw logical field names (normalize to your CIM
# before deploying). The hand-authored savedsearches.conf / correlation_searches.conf /
# sentinel/ forms alongside this file cover the enriched, absence/join, and Sentinel
# detections a bare compile can't emit.

[default]
dispatch.earliest_time = -60m
dispatch.latest_time = now
HEADER
  local d
  for d in "${WIN_DIRS[@]}"; do
    [[ -d "$SIGMA/$d" ]] || continue
    printf '\n### %s (splunk_windows)\n' "$d"
    gen_dir "$d" -p splunk_windows
  done
  for d in "${NONWIN_DIRS[@]}"; do
    [[ -d "$SIGMA/$d" ]] || continue
    printf '\n### %s (--without-pipeline)\n' "$d"
    gen_dir "$d" --without-pipeline
  done
}

if [[ "$CHECK" -eq 1 ]]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  generate >"$tmp"
  if ! diff -u "$OUT" "$tmp" >/dev/null 2>&1; then
    echo "gen-siem: $OUT is out of date — run detections/siem/gen-siem.sh" >&2
    diff -u "$OUT" "$tmp" >&2 || true
    exit 1
  fi
  echo "gen-siem: savedsearches.generated.conf up to date"
else
  generate >"$OUT"
  echo "gen-siem: wrote $OUT"
fi
