#!/usr/bin/env bash
# detections/siem/gen-siem.sh — generate the deployable SIEM forms from the Sigma
# source of truth, so the compiled deploy artifacts stop drifting by hand.
# ──────────────────────────────────────────────────────────────────────────────
# Sigma is the source of truth (detections/sigma/). This script is the reproducible
# "compile Sigma → backend, in its DEPLOY shape" step. It emits three artifacts, one
# per SIEM, each drift-gated in CI by `gen-siem.sh --check`:
#
#   splunk/savedsearches.generated.conf   Splunk savedsearches.conf stanzas (every
#                                         rule; Windows dirs via the splunk_windows TA
#                                         pipeline, non-Windows dirs raw)
#   sentinel/rules.generated.kql          Microsoft Sentinel KQL, one query per rule
#   elastic/rules.generated.lucene        Elasticsearch Lucene, one query per rule
#
# The KQL/Lucene forms compile each rule with `--without-pipeline` (raw logical field
# names) — a compile-checked deploy STARTING point, same framing as convert.sh. A real
# deploy adds a schema pipeline (sentinel_asim / microsoft_xdr for Sentinel, ecs_windows
# for Elastic) on the Windows rules. Rules a backend cannot express (Sigma correlations
# — password spray, AS-REP probing) are NOTED in the file, not silently dropped. The
# hand-authored siem/ forms (savedsearches.conf, correlation_searches.conf, sentinel/*.yaml)
# stay for the enriched, absence/join, and packaged-analytics deploys a bare compile can't emit.
#
#   gen-siem.sh            # (re)write all three generated artifacts from sigma/
#   gen-siem.sh --check    # exit 1 (with a diff) if any committed artifact is out of date
#
# Deps: sigma-cli + the pinned backends (splunk, elasticsearch, kusto) — see the CI job.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)"
SIGMA="$HERE/../sigma"
OUT_SPLUNK="$HERE/splunk/savedsearches.generated.conf"
OUT_SENTINEL="$HERE/sentinel/rules.generated.kql"
OUT_ELASTIC="$HERE/elastic/rules.generated.lucene"

CHECK=0
if [[ $# -gt 1 ]]; then
  echo "gen-siem: too many arguments" >&2
  echo "usage: gen-siem.sh [--check]" >&2
  exit 2
fi
case "${1:-}" in
"") CHECK=0 ;;
--check) CHECK=1 ;;
*)
  echo "gen-siem: unknown argument '$1'" >&2
  echo "usage: gen-siem.sh [--check]" >&2
  exit 2
  ;;
esac

if ! command -v sigma >/dev/null 2>&1; then
  echo "sigma not found — pip install sigma-cli pysigma-backend-splunk pysigma-backend-elasticsearch pysigma-backend-kusto" >&2
  exit 1
fi

# Windows tactic dirs → splunk_windows TA pipeline; non-Windows platform dirs → raw.
# (Same split convert.sh documents; kept explicit so a new dir is a conscious choice.)
WIN_DIRS=(credential_access privilege_escalation lateral_movement persistence defense_evasion)
NONWIN_DIRS=(cloud kubernetes okta github gitlab registry vault terraform jenkins snowflake google_workspace cloudflare npm pypi slack)

# ── Splunk savedsearches form ─────────────────────────────────────────────────
# Each `sigma convert -f savedsearches` invocation prepends its own [default] stanza
# (global dispatch window). Strip every per-invocation [default] block and emit one
# canonical [default] at the top instead. Skip from the [default] header until the NEXT
# stanza header (^[) — not the next blank line, which would be brittle if the upstream
# format ever reflowed blank lines.
strip_default() {
  awk '
    /^\[default\]$/ { skip=1; next }
    skip && /^\[/   { skip=0 }
    skip            { next }
    { print }
  '
}

# Compile one rule dir to savedsearches stanzas. Rules are passed as an explicit,
# byte-sorted file list (NOT the bare directory): `sigma convert <dir>` enumerates in
# filesystem order, which differs between machines and would make the generated file —
# and therefore the --check drift gate — non-reproducible across environments.
gen_dir() {
  local dir="$1"
  shift
  [[ -d "$SIGMA/$dir" ]] || return 0
  local files=()
  mapfile -t files < <(find "$SIGMA/$dir" -maxdepth 1 -name '*.yml' | LC_ALL=C sort)
  [[ ${#files[@]} -gt 0 ]] || return 0
  # No stderr suppression: sigma's "Parsing Sigma rules" notice goes to stderr (it does
  # not pollute the generated stdout), and a real conversion error must stay visible.
  sigma convert -t splunk -f savedsearches "$@" "${files[@]}" | strip_default
}

generate_splunk() {
  cat <<'HEADER'
# savedsearches.generated.conf — GENERATED by detections/siem/gen-siem.sh. DO NOT EDIT.
#
# Reproducible compile of every Sigma rule in detections/sigma/ to its Splunk
# savedsearches deploy form. Regenerate with detections/siem/gen-siem.sh; CI drift-gates
# it with `gen-siem.sh --check`. Windows dirs use the splunk_windows TA pipeline; the
# non-Windows platform dirs compile with raw logical field names (normalize to your CIM
# before deploying). The hand-authored savedsearches.conf / correlation_searches.conf /
# sentinel/ forms alongside this file cover the enriched, absence/join, and Sentinel
# detections a bare compile can't emit.

[default]
dispatch.earliest_time = -60m
dispatch.latest_time = now
HEADER
  local d
  for d in "${WIN_DIRS[@]}"; do
    [[ -d "$SIGMA/$d" ]] || continue
    printf '\n### %s (splunk_windows)\n' "$d"
    gen_dir "$d" -p splunk_windows
  done
  for d in "${NONWIN_DIRS[@]}"; do
    [[ -d "$SIGMA/$d" ]] || continue
    printf '\n### %s (--without-pipeline)\n' "$d"
    gen_dir "$d" --without-pipeline
  done
}

# ── Sentinel (KQL) / Elastic (Lucene) forms ───────────────────────────────────
# Every rule as its own query, compiled --without-pipeline. Per-rule (not per-dir):
# a single unconvertible rule aborts a whole-dir convert, and per-rule lets us NOTE the
# ones a backend can't express (Sigma correlations) instead of dropping them silently.
all_rules() { find "$SIGMA" -mindepth 2 -maxdepth 2 -name '*.yml' | LC_ALL=C sort; }

# The kusto backend, compiled --without-pipeline, quotes dotted field identifiers with
# SINGLE quotes (e.g. 'resource.type') — but single quotes are STRING LITERALS in KQL, so
# the predicate wouldn't reference a column; it also renders booleans as `=~ true`. Since
# string VALUES are double-quoted, single-quoted tokens are unambiguously field names:
# rewrite them to bracketed column refs (['resource.type']) and fix the boolean operator,
# yielding syntactically valid KQL. (Elastic/Lucene needs no such fix — dots are legal there.)
kql_fix() {
  sed -E "s/''+/'/g; s/'([A-Za-z0-9_.]+)'/['\1']/g; s/=~ (true|false)/== \1/g"
}

emit_queries() {
  # Subshell + EXIT trap: the stderr-capture temp is removed exactly when this call's work
  # finishes (normal OR aborted), scoped to the subshell. A `trap … RETURN` is GLOBAL in bash
  # — it would keep firing on every later function return and expand the now-out-of-scope
  # $errf under `set -u`.
  (
    local target="$1" label="$2" comment="$3" f rel title q errf
    errf="$(mktemp)"
    trap 'rm -f "$errf"' EXIT
    printf '%s rules.generated — GENERATED by detections/siem/gen-siem.sh. DO NOT EDIT.\n' "$comment"
    printf '%s %s deploy form: each Sigma rule in detections/sigma/ compiled with\n' "$comment" "$label"
    printf '%s   sigma convert -t %s --without-pipeline\n' "$comment" "$target"
    printf '%s (raw logical field names — for a real deploy add a schema pipeline, e.g.\n' "$comment"
    printf '%s sentinel_asim/microsoft_xdr for Sentinel or ecs_windows for Elastic on the\n' "$comment"
    printf '%s Windows rules). Regenerate with detections/siem/gen-siem.sh; CI drift-gates it.\n' "$comment"
    printf '%s Rules a backend cannot express (Sigma correlations) are noted, not dropped.\n' "$comment"
    while IFS= read -r f; do
      rel="${f#"$SIGMA"/}"
      title="$(sed -n 's/^title:[[:space:]]*//p' "$f" | head -1)"
      printf '\n%s %s — %s\n' "$comment" "$rel" "$title"
      if q="$(sigma convert -t "$target" --without-pipeline "$f" 2>"$errf")"; then
        if [[ "$target" == kusto ]]; then q="$(printf '%s' "$q" | kql_fix)"; fi
        printf '%s\n' "$q"
      else
        printf '%s UNSUPPORTED: %s\n' "$comment" "$(sed -n 's/^Error: //p' "$errf" | head -1)"
      fi
    done < <(all_rules)
  )
}

render_one() {
  case "$1" in
  splunk) generate_splunk ;;
  sentinel) emit_queries kusto "Microsoft Sentinel (KQL)" '//' ;;
  elastic) emit_queries lucene "Elasticsearch (Lucene)" '//' ;;
  esac
}
outpath() {
  case "$1" in
  splunk) echo "$OUT_SPLUNK" ;;
  sentinel) echo "$OUT_SENTINEL" ;;
  elastic) echo "$OUT_ELASTIC" ;;
  esac
}

WHICH=(splunk sentinel elastic)

if [[ "$CHECK" -eq 1 ]]; then
  rc=0
  trap 'rm -f "${tmp:-}"' EXIT # remove the compare temp even on a set -e abort mid-loop
  for w in "${WHICH[@]}"; do
    out="$(outpath "$w")"
    tmp="$(mktemp)"
    render_one "$w" >"$tmp"
    if ! diff -u "$out" "$tmp" >/dev/null 2>&1; then
      echo "gen-siem: $out is out of date — run detections/siem/gen-siem.sh" >&2
      diff -u "$out" "$tmp" >&2 || true
      rc=1
    fi
    rm -f "$tmp"
  done
  if [[ "$rc" -eq 0 ]]; then
    echo "gen-siem: all generated SIEM forms up to date"
  fi
  exit "$rc"
else
  for w in "${WHICH[@]}"; do
    out="$(outpath "$w")"
    mkdir -p "$(dirname "$out")"
    render_one "$w" >"$out"
    echo "gen-siem: wrote $out"
  done
fi
