# cryptomine-pool-feed.zeek — GENERATED by detections/network/update-pool-feed.sh. DO NOT EDIT.
# Source: not yet fetched — run detections/network/update-pool-feed.sh to populate.
# 0 known mining-pool address(es). @load next to cryptomine-pool.zeek.
# Regenerate with update-pool-feed.sh after refreshing the feed; commit the result.
# (feed carried no addresses — nothing to add; the set stays empty)
