# ja3-c2-feed.zeek — GENERATED by detections/network/update-ja3-feed.sh. DO NOT EDIT.
# Source: not yet fetched — run detections/network/update-ja3-feed.sh to populate.
# 0 known-C2 JA3 fingerprint(s). @load'd by tls-c2-ja3.zeek (the opt-in JA3 path).
# Regenerate with update-ja3-feed.sh after refreshing the feed; commit the result.
# (feed carried no fingerprints — nothing to add; the set stays empty)
