#!/usr/bin/env bash
# update-ja3-feed.sh — refresh the known-C2 JA3 fingerprint feed the tls-c2 detections use.
# ──────────────────────────────────────────────────────────────────────────────
# The JA3 fast path (zeek/tls-c2-ja3.zeek + the commented dataset rule in
# suricata/c2.rules) matches TLS handshakes against a blocklist of C2-framework JA3
# fingerprints. Those hashes ROTATE, so the repo does not hard-code them — this script
# pulls a maintained feed and regenerates both engines' data files from it:
#
#   zeek/ja3-c2-feed.zeek   a `redef TLSC2JA3::c2_ja3_blocklist += { ... }` fragment
#                           (@load'd by tls-c2-ja3.zeek) — pure comments when empty
#   suricata/ja3-c2.lst     a Suricata `dataset` file: base64 of each ja3.hash string,
#                           one per line (the encoding `type string` datasets expect)
#
#   update-ja3-feed.sh                     # fetch the default feed, regenerate both
#   update-ja3-feed.sh --url <feed-url>    # use a different CSV/text feed
#   update-ja3-feed.sh --from-file <path>  # parse a local file (offline / testing)
#   JA3_FEED_URL=<url> update-ja3-feed.sh  # same as --url, via env
#
# The parser is format-tolerant: it extracts every 32-hex JA3 md5 it sees (skipping the
# CSV's comment/header lines), lowercases, de-duplicates, and sorts — so the output is
# deterministic (re-running on the same feed produces an identical diff) and survives
# minor feed-format changes. Commit the regenerated files so the fleet stays in sync.
# An empty feed yields an empty blocklist, which matches nothing — safe by construction.
#
# Default feed: abuse.ch SSLBL JA3 fingerprint blocklist. Swap it for Proofpoint ET, a
# vendor feed, or your own lab captures with --url. bash 3.2-safe (macOS stock bash).
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)"
ZEEK_OUT="$HERE/zeek/ja3-c2-feed.zeek"
SURICATA_OUT="$HERE/suricata/ja3-c2.lst"

DEFAULT_URL="https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv"
URL="${JA3_FEED_URL:-$DEFAULT_URL}"
FROM_FILE=""

usage() {
  sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
  --url) URL="${2:?--url needs a value}"; shift 2 ;;
  --from-file) FROM_FILE="${2:?--from-file needs a value}"; shift 2 ;;
  -h | --help) usage; exit 0 ;;
  *)
    echo "update-ja3-feed: unknown argument '$1'" >&2
    exit 2
    ;;
  esac
done

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

if [[ -n "$FROM_FILE" ]]; then
  cp -- "$FROM_FILE" "$tmp"
  src="$FROM_FILE"
else
  if ! command -v curl >/dev/null 2>&1; then
    echo "update-ja3-feed: curl not found (or pass --from-file)" >&2
    exit 1
  fi
  echo "update-ja3-feed: fetching $URL" >&2
  curl -fsSL --retry 3 -- "$URL" >"$tmp"
  src="$URL"
fi

# Extract 32-hex JA3 md5s, lowercase, de-duplicate, sort. Robust to CSV/comment format.
hashes=()
while IFS= read -r h; do
  hashes+=("$h")
done < <(grep -oiE '[0-9a-fA-F]{32}' -- "$tmp" | tr '[:upper:]' '[:lower:]' | sort -u)
n="${#hashes[@]}"

# --- Zeek fragment: a redef of the opt-in set (pure comments when empty). ---
{
  echo "# ja3-c2-feed.zeek — GENERATED by detections/network/update-ja3-feed.sh. DO NOT EDIT."
  echo "# Source: $src"
  echo "# ${n} known-C2 JA3 fingerprint(s). @load'd by tls-c2-ja3.zeek (the opt-in JA3 path)."
  echo "# Regenerate with update-ja3-feed.sh after refreshing the feed; commit the result."
  if [[ "$n" -gt 0 ]]; then
    echo "redef TLSC2JA3::c2_ja3_blocklist += {"
    for h in "${hashes[@]}"; do
      printf '\t"%s",\n' "$h"
    done
    echo "};"
  else
    echo "# (feed carried no fingerprints — nothing to add; the set stays empty)"
  fi
} >"$ZEEK_OUT"

# --- Suricata dataset: base64 of each ja3.hash string, one per line (empty = empty set). ---
: >"$SURICATA_OUT"
if [[ "$n" -gt 0 ]]; then
  for h in "${hashes[@]}"; do
    printf '%s' "$h" | base64
  done >>"$SURICATA_OUT"
fi

echo "update-ja3-feed: wrote $n fingerprint(s):" >&2
echo "  ${ZEEK_OUT#"$HERE"/}" >&2
echo "  ${SURICATA_OUT#"$HERE"/}" >&2
