#!/usr/bin/env bash
# update-pool-feed.sh — refresh the known mining-pool address feed cryptomine-pool uses.
# ──────────────────────────────────────────────────────────────────────────────
# zeek/cryptomine-pool.zeek finds an UNKNOWN pool behaviourally (Stratum port + long,
# low-rate session). That test cannot see a pool reached over 443, because the port is
# the thing it keys on. This feed is the fallback for exactly that case: a set of known
# pool ADDRESSES, matched on any port.
#
# Pool infrastructure rotates, so the repo does not hard-code it — this script pulls a
# maintained feed and regenerates the engines' data files:
#
#   zeek/cryptomine-pool-feed.zeek   a `redef CryptoMine::pool_hosts += { ... }` fragment
#                                    (@load'd next to cryptomine-pool.zeek) — pure
#                                    comments when empty
#   suricata/cryptomine-pool.lst     one address per line, for the (commented) dataset
#                                    rule in suricata/cryptomine.rules
#
#   update-pool-feed.sh                     # fetch the default feed, regenerate both
#   update-pool-feed.sh --url <feed-url>    # use a different feed
#   update-pool-feed.sh --from-file <path>  # parse a local file (offline / testing)
#   POOL_FEED_URL=<url> update-pool-feed.sh # same as --url, via env
#
# Same design as update-ja3-feed.sh, deliberately — that script already solved this
# problem and a second mechanism would be a second thing to maintain. The parser is
# format-tolerant: it extracts every IPv4 literal it sees, de-duplicates, and sorts, so
# output is deterministic (re-running on the same feed produces an identical diff) and
# survives minor feed-format changes. An empty feed yields an empty set, which matches
# nothing — safe by construction, so nothing goes stale or false-positives.
#
# NOTE ON DEFAULT: unlike JA3, there is no single canonical pool blocklist. The default
# below is a widely-mirrored community list; treat it as a starting point and prefer your
# own threat-intel feed via --url. Commit the regenerated files so the fleet stays in sync.
# bash 3.2-safe (macOS stock bash).
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# No `dirname --`: BSD/macOS dirname doesn't reliably take `--`, and the argument is
# always a script path (never starts with `-`), so it's unneeded. Unset CDPATH so a cd
# in the caller's environment can't print the target dir into HERE.
unset CDPATH
HERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
ZEEK_OUT="$HERE/zeek/cryptomine-pool-feed.zeek"
SURICATA_OUT="$HERE/suricata/cryptomine-pool.lst"

DEFAULT_URL="https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/malware/cryptocurrency_mining.txt"
URL="${POOL_FEED_URL:-$DEFAULT_URL}"
FROM_FILE=""

usage() {
  sed -n '2,34p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
  --url) URL="${2:?--url needs a value}"; shift 2 ;;
  --from-file) FROM_FILE="${2:?--from-file needs a value}"; shift 2 ;;
  -h | --help) usage; exit 0 ;;
  *)
    echo "update-pool-feed: unknown argument '$1'" >&2
    exit 2
    ;;
  esac
done

# Parse either the given file directly or a fetched temp copy — no `cp` needed. mktemp
# takes an explicit template so it's portable (BSD mktemp errors without one; GNU doesn't).
tmp=""
# return 0 so this (the EXIT trap) never overrides the script's real exit status — the
# guard returns 1 when $tmp is empty (from-file mode), which would otherwise leak out.
cleanup() {
  [[ -n "$tmp" ]] && rm -f "$tmp"
  return 0
}
trap cleanup EXIT

if [[ -n "$FROM_FILE" ]]; then
  input="$FROM_FILE"
  src="$FROM_FILE"
else
  if ! command -v curl >/dev/null 2>&1; then
    echo "update-pool-feed: curl not found (or pass --from-file)" >&2
    exit 1
  fi
  tmp="$(mktemp "${TMPDIR:-/tmp}/pool-feed.XXXXXX")"
  echo "update-pool-feed: fetching $URL" >&2
  curl -fsSL --retry 3 "$URL" >"$tmp"
  input="$tmp"
  src="$URL"
fi

# Extract IPv4 literals, de-duplicate, sort. `sort -u -t. -k1,1n -k2,2n -k3,3n -k4,4n`
# would order them numerically, but plain `sort -u` is what makes the diff STABLE across
# platforms (BSD and GNU sort agree on byte order, not on numeric-field parsing of mixed
# input), and stability is what this file needs.
addrs=()
while IFS= read -r a; do
  addrs+=("$a")
done < <(grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' -- "$input" | sort -u)
n="${#addrs[@]}"

# --- Zeek fragment: a redef of the pool set (pure comments when empty). ---
{
  echo "# cryptomine-pool-feed.zeek — GENERATED by detections/network/update-pool-feed.sh. DO NOT EDIT."
  echo "# Source: $src"
  echo "# ${n} known mining-pool address(es). @load next to cryptomine-pool.zeek."
  echo "# Regenerate with update-pool-feed.sh after refreshing the feed; commit the result."
  if [[ "$n" -gt 0 ]]; then
    echo "redef CryptoMine::pool_hosts += {"
    for a in "${addrs[@]}"; do
      printf '\t%s,\n' "$a"
    done
    echo "};"
  else
    echo "# (feed carried no addresses — nothing to add; the set stays empty)"
  fi
} >"$ZEEK_OUT"

# --- Suricata dataset: one address per line (empty = empty set). ---
: >"$SURICATA_OUT"
if [[ "$n" -gt 0 ]]; then
  for a in "${addrs[@]}"; do
    printf '%s\n' "$a"
  done >>"$SURICATA_OUT"
fi

echo "update-pool-feed: wrote $n address(es):" >&2
echo "  ${ZEEK_OUT#"$HERE"/}" >&2
echo "  ${SURICATA_OUT#"$HERE"/}" >&2
